//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amptron.Resources.Raw {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amptron.Resources.Raw.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is a leader in high performance energy storage solutions, supplying Lithium batteries, chargers, power monitors, solar panels and portable power packs..
        /// </summary>
        internal static string AboutUs_Content1 {
            get {
                return ResourceManager.GetString("AboutUs_Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  can be used as an AR “Alternative Replacement” for deep cycle Lead Acid, Gel or AGM Batteries. .
        /// </summary>
        internal static string AboutUs_Content2 {
            get {
                return ResourceManager.GetString("AboutUs_Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  trust and depend on us for our high quality, safe and reliable technology..
        /// </summary>
        internal static string AboutUs_Content3 {
            get {
                return ResourceManager.GetString("AboutUs_Content3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium LiFePO4 Batteries.
        /// </summary>
        internal static string AboutUs_LithiumBatteries {
            get {
                return ResourceManager.GetString("AboutUs_LithiumBatteries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our .
        /// </summary>
        internal static string AboutUs_Our {
            get {
                return ResourceManager.GetString("AboutUs_Our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our customers.
        /// </summary>
        internal static string AboutUs_OurCustomers {
            get {
                return ResourceManager.GetString("AboutUs_OurCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Device.
        /// </summary>
        internal static string AddDevice {
            get {
                return ResourceManager.GetString("AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Page.
        /// </summary>
        internal static string AlarmPage {
            get {
                return ResourceManager.GetString("AlarmPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMPTRON®.
        /// </summary>
        internal static string AmptronReserved {
            get {
                return ResourceManager.GetString("AmptronReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balancing Status.
        /// </summary>
        internal static string BalancingStatus {
            get {
                return ResourceManager.GetString("BalancingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Life.
        /// </summary>
        internal static string BatteryLife {
            get {
                return ResourceManager.GetString("BatteryLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMS Temp.
        /// </summary>
        internal static string BMSTemp {
            get {
                return ResourceManager.GetString("BMSTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Temp.
        /// </summary>
        internal static string CellTemp {
            get {
                return ResourceManager.GetString("CellTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cfet_off.
        /// </summary>
        internal static string Cfet_off {
            get {
                return ResourceManager.GetString("Cfet_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Switch.
        /// </summary>
        internal static string ChargeSwitch {
            get {
                return ResourceManager.GetString("ChargeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your mail.
        /// </summary>
        internal static string CheckYourMail {
            get {
                return ResourceManager.GetString("CheckYourMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to get started!.
        /// </summary>
        internal static string CreateAccountInfo {
            get {
                return ResourceManager.GetString("CreateAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed View.
        /// </summary>
        internal static string DetailedView {
            get {
                return ResourceManager.GetString("DetailedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Code.
        /// </summary>
        internal static string DeviceCode {
            get {
                return ResourceManager.GetString("DeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Info.
        /// </summary>
        internal static string DeviceInfo {
            get {
                return ResourceManager.GetString("DeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device List.
        /// </summary>
        internal static string DeviceList {
            get {
                return ResourceManager.GetString("DeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Model.
        /// </summary>
        internal static string DeviceModel {
            get {
                return ResourceManager.GetString("DeviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dfet_off.
        /// </summary>
        internal static string Dfet_off {
            get {
                return ResourceManager.GetString("Dfet_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge Current.
        /// </summary>
        internal static string DischargeCurrent {
            get {
                return ResourceManager.GetString("DischargeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge Switch.
        /// </summary>
        internal static string DischargeSwitch {
            get {
                return ResourceManager.GetString("DischargeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem Ipsum is simply dummy text of the printing and typesetting industry..
        /// </summary>
        internal static string DummyTextContent {
            get {
                return ResourceManager.GetString("DummyTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem Ipsum is simply dummy text of the printing and typesetting industry..
        /// </summary>
        internal static string DummyTextTitle {
            get {
                return ResourceManager.GetString("DummyTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Photo.
        /// </summary>
        internal static string EditPhoto {
            get {
                return ResourceManager.GetString("EditPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Login.
        /// </summary>
        internal static string GuestLogin {
            get {
                return ResourceManager.GetString("GuestLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        internal static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobileNumber.
        /// </summary>
        internal static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Device.
        /// </summary>
        internal static string NameOfTheDevice {
            get {
                return ResourceManager.GetString("NameOfTheDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Devices Found.
        /// </summary>
        internal static string NoDevicesFound {
            get {
                return ResourceManager.GetString("NoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t see the product you were looking for ?.
        /// </summary>
        internal static string NoDevicesFoundInfo {
            get {
                return ResourceManager.GetString("NoDevicesFoundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Cycles.
        /// </summary>
        internal static string NoOfCycles {
            get {
                return ResourceManager.GetString("NoOfCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the AMPTRON® Link App. The app’s main functionality is to monitor details of the Amptron BluPower batteries. .
        /// </summary>
        internal static string Onboarding_View1Content {
            get {
                return ResourceManager.GetString("Onboarding_View1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First search for a device on the Device list page and connect to the device. To switch between devices, select a different device on the list. .
        /// </summary>
        internal static string Onboarding_View2Content {
            get {
                return ResourceManager.GetString("Onboarding_View2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open email app.
        /// </summary>
        internal static string OpenEmailApp {
            get {
                return ResourceManager.GetString("OpenEmailApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection Alarms.
        /// </summary>
        internal static string ProtectionAlarms {
            get {
                return ResourceManager.GetString("ProtectionAlarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        internal static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol Ver.
        /// </summary>
        internal static string ProtocolVer {
            get {
                return ResourceManager.GetString("ProtocolVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated Capacity.
        /// </summary>
        internal static string RatedCapacity {
            get {
                return ResourceManager.GetString("RatedCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Capacity.
        /// </summary>
        internal static string RemainingCapacity {
            get {
                return ResourceManager.GetString("RemainingCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Password.
        /// </summary>
        internal static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email associated with your account and we&apos;ll send an email with instructions to reset your password..
        /// </summary>
        internal static string ResetPasswordInfo {
            get {
                return ResourceManager.GetString("ResetPasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Status.
        /// </summary>
        internal static string RunningStatus {
            get {
                return ResourceManager.GetString("RunningStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Id/Name.
        /// </summary>
        internal static string SearchByNameOrId {
            get {
                return ResourceManager.GetString("SearchByNameOrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Instructions.
        /// </summary>
        internal static string SendInstructions {
            get {
                return ResourceManager.GetString("SendInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent a password recover instructions to your email..
        /// </summary>
        internal static string SentMailInfo {
            get {
                return ResourceManager.GetString("SentMailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN Code.
        /// </summary>
        internal static string SNCode {
            get {
                return ResourceManager.GetString("SNCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOH%.
        /// </summary>
        internal static string SOHPercentage {
            get {
                return ResourceManager.GetString("SOHPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Form.
        /// </summary>
        internal static string SubmitForm {
            get {
                return ResourceManager.GetString("SubmitForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your Question.
        /// </summary>
        internal static string SubmitYourQuestion {
            get {
                return ResourceManager.GetString("SubmitYourQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Alarms.
        /// </summary>
        internal static string TemperatureAlarms {
            get {
                return ResourceManager.GetString("TemperatureAlarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Status.
        /// </summary>
        internal static string TempStatus {
            get {
                return ResourceManager.GetString("TempStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        internal static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
    }
}
